# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

############################
# S3
############################

resource "aws_s3_bucket" "flip_bucket" {
  bucket = var.FLIP_BUCKET_NAME
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket_cors_configuration" "flip_bucket_cors" {
  bucket = aws_s3_bucket.flip_bucket.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT"]
    allowed_origins = ["*"]
    expose_headers  = []
  }
}

# Model files uploaded by researchers will be combined with the base app here
resource "aws_s3_object" "app_destination_bucket" {
  bucket  = aws_s3_bucket.flip_bucket.id
  key     = "app_destination_bucket/"
  content = ""
  lifecycle {
    prevent_destroy = true
  }
}

# Model files uploaded by researchers will be stored here
resource "aws_s3_object" "model_files" {
  bucket  = aws_s3_bucket.flip_bucket.id
  key     = "model_files/"
  content = ""
  lifecycle {
    prevent_destroy = true
  }
}

# FL results will be stored here
resource "aws_s3_object" "uploaded_federated_data" {
  bucket  = aws_s3_bucket.flip_bucket.id
  key     = "uploaded_federated_data/"
  content = ""
  lifecycle {
    prevent_destroy = true
  }
}

############################
# AI Centre S3 Bucket
############################

resource "aws_s3_bucket" "aicentre_bucket" {
  bucket = var.AICENTRE_BUCKET_NAME
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket_cors_configuration" "aicentre_bucket_cors" {
  bucket = aws_s3_bucket.aicentre_bucket.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "GET"]
    allowed_origins = ["*"]
    expose_headers  = []
  }
}

############################
# Cognito
############################

resource "aws_cognito_user_pool" "flip_user_pool" {
  name                     = var.flip_user_pool_name
  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]
  schema {
    name                = "email"
    attribute_data_type = "String"
    mutable             = false
    required            = true
  }

  # Cognito email templates for admin-created users and password reset flows
  # See: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/userguide/user-pool-email.html
  # Color scheme matches flip-ui: https://github.com/londonaicentre/FLIP/blob/develop/flip-ui/tailwind.config.js
  # Primary: #61366e (purple), Secondary: #9452A8 (lighter purple), Accent: #301A37 (dark purple)
  admin_create_user_config {
    invite_message_template {
      # {username} placeholder: Cognito username for the invited user
      # {####} placeholder: 6-character temporary password generated by Cognito
      email_subject = "Welcome to FLIP – Federated Learning and Interoperability Platform"
      email_message = <<-EOT
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
        </head>
        <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, 'Helvetica Neue', sans-serif; background-color: #f5f5f5;">
          <table cellpadding="0" cellspacing="0" width="100%" style="background-color: #f5f5f5;">
            <tr>
              <td style="padding: 40px 20px;">
                <!-- Main container -->
                <table cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow: hidden;">
                  <!-- Header with gradient background -->
                  <tr>
                    <td style="background: linear-gradient(135deg, #61366e 0%, #9452A8 100%); padding: 40px 30px; text-align: center;">
                      <!-- Logo placeholder - replace with actual hosted logo URL -->
                      <!-- <img src="https://your-cdn.com/flip-logo.svg" alt="FLIP Logo" style="height: 50px; margin-bottom: 20px;"> -->
                      <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700; letter-spacing: -0.5px;">FLIP</h1>
                      <p style="margin: 8px 0 0 0; color: rgba(255,255,255,0.9); font-size: 14px; font-weight: 500;">Federated Learning & Interoperability Platform</p>
                    </td>
                  </tr>
                  
                  <!-- Content section -->
                  <tr>
                    <td style="padding: 40px 30px;">
                      <!-- Personalized greeting -->
                      <p style="margin: 0 0 24px 0; color: #301A37; font-size: 16px; line-height: 1.5;">Hello <strong>{username}</strong>,</p>
                      
                      <!-- Welcome message -->
                      <p style="margin: 0 0 24px 0; color: #434757; font-size: 16px; line-height: 1.6;">You have been invited to join <strong>FLIP</strong> (Federated Learning and Interoperability Platform), hosted by the London AI Centre.</p>
                      
                      <!-- Credentials section -->
                      <div style="background-color: #F7F3F9; border-left: 4px solid #9452A8; padding: 20px; margin: 24px 0; border-radius: 4px;">
                        <p style="margin: 0 0 16px 0; color: #301A37; font-size: 14px; font-weight: 600;">Your temporary login credentials:</p>
                        <table cellpadding="0" cellspacing="0" width="100%">
                          <tr>
                            <td style="padding: 8px 0; color: #61366e; font-weight: 600; width: 120px; font-size: 14px;">Username:</td>
                            <td style="padding: 8px 0; color: #301A37; font-family: 'Monaco', 'Courier New', monospace; font-size: 14px; word-break: break-word;">{username}</td>
                          </tr>
                          <tr>
                            <td style="padding: 8px 0; color: #61366e; font-weight: 600; font-size: 14px;">Temporary password:</td>
                            <td style="padding: 8px 0; color: #301A37; font-family: 'Monaco', 'Courier New', monospace; font-size: 16px; letter-spacing: 2px; font-weight: 600;">{####}</td>
                          </tr>
                        </table>
                      </div>
                      
                      <!-- Action instructions -->
                      <p style="margin: 24px 0 16px 0; color: #434757; font-size: 16px; line-height: 1.6;">Please sign in and change your password on first login:</p>
                      
                      <!-- CTA Button -->
                      <table cellpadding="0" cellspacing="0" style="margin: 24px 0;">
                        <tr>
                          <td style="background-color: #61366e; border-radius: 6px; text-align: center; padding: 0;">
                            <a href="https://${var.flip_alb_subdomain}" style="display: inline-block; padding: 12px 32px; color: #ffffff; text-decoration: none; font-weight: 600; font-size: 16px;">Sign In to FLIP</a>
                          </td>
                        </tr>
                      </table>
                      
                      <!-- Footer message -->
                      <p style="margin: 24px 0 8px 0; color: #9452A8; font-size: 14px; line-height: 1.5;">If you did not expect this invitation, you can safely ignore this email.</p>
                    </td>
                  </tr>
                  
                  <!-- Footer -->
                  <tr>
                    <td style="background-color: #f9f9f9; padding: 24px 30px; border-top: 1px solid #eeeeee; text-align: center;">
                      <p style="margin: 0 0 8px 0; color: #9452A8; font-size: 13px; font-weight: 600;">The FLIP Team</p>
                      <p style="margin: 0; color: #999999; font-size: 12px;">Federated Learning and Interoperability Platform</p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </body>
        </html>
      EOT
      # SMS fallback message for users without email or additional verification
      sms_message   = "You've been invited to FLIP. Username: {username}, Temporary password: {####}. Sign in at https://${var.flip_alb_subdomain}"
    }
  }

  # Cognito email templates for password reset and account verification flows
  verification_message_template {
    default_email_option  = "CONFIRM_WITH_CODE"
    email_subject         = "Password Reset Request – FLIP"
    # {####} placeholder: 6-character verification code for password reset
    email_message         = <<-EOT
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, 'Helvetica Neue', sans-serif; background-color: #f5f5f5;">
        <table cellpadding="0" cellspacing="0" width="100%" style="background-color: #f5f5f5;">
          <tr>
            <td style="padding: 40px 20px;">
              <!-- Main container -->
              <table cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow: hidden;">
                <!-- Header with gradient background -->
                <tr>
                  <td style="background: linear-gradient(135deg, #61366e 0%, #9452A8 100%); padding: 40px 30px; text-align: center;">
                    <!-- Logo placeholder - replace with actual hosted logo URL -->
                    <!-- <img src="https://your-cdn.com/flip-logo.svg" alt="FLIP Logo" style="height: 50px; margin-bottom: 20px;"> -->
                    <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700; letter-spacing: -0.5px;">FLIP</h1>
                    <p style="margin: 8px 0 0 0; color: rgba(255,255,255,0.9); font-size: 14px; font-weight: 500;">Security & Account Management</p>
                  </td>
                </tr>
                
                <!-- Content section -->
                <tr>
                  <td style="padding: 40px 30px;">
                    <!-- Alert message -->
                    <p style="margin: 0 0 24px 0; color: #301A37; font-size: 16px; line-height: 1.5;">Hello,</p>
                    
                    <!-- Password reset message -->
                    <p style="margin: 0 0 24px 0; color: #434757; font-size: 16px; line-height: 1.6;">We received a request to reset your password for your <strong>FLIP</strong> (Federated Learning and Interoperability Platform) account.</p>
                    
                    <!-- Verification code section -->
                    <div style="background-color: #F7F3F9; border-left: 4px solid #9452A8; padding: 24px; margin: 24px 0; border-radius: 4px; text-align: center;">
                      <p style="margin: 0 0 16px 0; color: #61366e; font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;">Your verification code:</p>
                      <p style="margin: 0; color: #301A37; font-family: 'Monaco', 'Courier New', monospace; font-size: 32px; letter-spacing: 4px; font-weight: 700; word-spacing: 8px;">{####}</p>
                      <p style="margin: 12px 0 0 0; color: #9452A8; font-size: 13px;">Valid for 24 hours</p>
                    </div>
                    
                    <!-- Security notice -->
                    <div style="background-color: #FEF3F2; border-left: 4px solid #E51170; padding: 16px; margin: 24px 0; border-radius: 4px;">
                      <p style="margin: 0; color: #BF360C; font-size: 14px; line-height: 1.5;"><strong>⚠️ Security Tip:</strong> If you did not request this password reset, your account may be at risk. Please contact support immediately.</p>
                    </div>
                    
                    <!-- Closing message -->
                    <p style="margin: 24px 0 0 0; color: #434757; font-size: 14px; line-height: 1.6;">If you did not request a password reset, you can safely ignore this email. Your password will remain unchanged.</p>
                  </td>
                </tr>
                
                <!-- Footer -->
                <tr>
                  <td style="background-color: #f9f9f9; padding: 24px 30px; border-top: 1px solid #eeeeee; text-align: center;">
                    <p style="margin: 0 0 8px 0; color: #9452A8; font-size: 13px; font-weight: 600;">The FLIP Team</p>
                    <p style="margin: 0; color: #999999; font-size: 12px;">Federated Learning and Interoperability Platform</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
      </html>
    EOT
    email_subject_by_link = "Password Reset – FLIP"
    # {##...##} placeholder: Dynamically generated password reset link token
    email_message_by_link = <<-EOT
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, 'Helvetica Neue', sans-serif; background-color: #f5f5f5;">
        <table cellpadding="0" cellspacing="0" width="100%" style="background-color: #f5f5f5;">
          <tr>
            <td style="padding: 40px 20px;">
              <!-- Main container -->
              <table cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow: hidden;">
                <!-- Header with gradient background -->
                <tr>
                  <td style="background: linear-gradient(135deg, #61366e 0%, #9452A8 100%); padding: 40px 30px; text-align: center;">
                    <!-- Logo placeholder - replace with actual hosted logo URL -->
                    <!-- <img src="https://your-cdn.com/flip-logo.svg" alt="FLIP Logo" style="height: 50px; margin-bottom: 20px;"> -->
                    <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700; letter-spacing: -0.5px;">FLIP</h1>
                    <p style="margin: 8px 0 0 0; color: rgba(255,255,255,0.9); font-size: 14px; font-weight: 500;">Security & Account Management</p>
                  </td>
                </tr>
                
                <!-- Content section -->
                <tr>
                  <td style="padding: 40px 30px;">
                    <!-- Alert message -->
                    <p style="margin: 0 0 24px 0; color: #301A37; font-size: 16px; line-height: 1.5;">Hello,</p>
                    
                    <!-- Password reset message -->
                    <p style="margin: 0 0 24px 0; color: #434757; font-size: 16px; line-height: 1.6;">We received a request to reset your password for your <strong>FLIP</strong> (Federated Learning and Interoperability Platform) account.</p>
                    
                    <!-- Action instructions -->
                    <p style="margin: 0 0 24px 0; color: #434757; font-size: 16px; line-height: 1.6;">Click the button below to reset your password:</p>
                    
                    <!-- CTA Button -->
                    <table cellpadding="0" cellspacing="0" style="margin: 24px 0;">
                      <tr>
                        <td style="background-color: #61366e; border-radius: 6px; text-align: center; padding: 0;">
                          <a href="{##Click here to reset your password##}" style="display: inline-block; padding: 12px 32px; color: #ffffff; text-decoration: none; font-weight: 600; font-size: 16px;">Reset Password</a>
                        </td>
                      </tr>
                    </table>
                    
                    <!-- Security notice -->
                    <div style="background-color: #FEF3F2; border-left: 4px solid #E51170; padding: 16px; margin: 24px 0; border-radius: 4px;">
                      <p style="margin: 0; color: #BF360C; font-size: 14px; line-height: 1.5;"><strong>⚠️ Security Tip:</strong> If you did not request this password reset, your account may be at risk. Please contact support immediately.</p>
                    </div>
                    
                    <!-- Closing message -->
                    <p style="margin: 24px 0 0 0; color: #434757; font-size: 14px; line-height: 1.6;">If you did not request a password reset, you can safely ignore this email. Your password will remain unchanged.</p>
                  </td>
                </tr>
                
                <!-- Footer -->
                <tr>
                  <td style="background-color: #f9f9f9; padding: 24px 30px; border-top: 1px solid #eeeeee; text-align: center;">
                    <p style="margin: 0 0 8px 0; color: #9452A8; font-size: 13px; font-weight: 600;">The FLIP Team</p>
                    <p style="margin: 0; color: #999999; font-size: 12px;">Federated Learning and Interoperability Platform</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
      </html>
    EOT
    # SMS fallback message for verification code delivery
    sms_message           = "Your FLIP password reset code is: {####}. Valid for 24 hours."
  }

  deletion_protection = "ACTIVE"
  lifecycle {
    prevent_destroy = true
  }
}

resource "random_string" "cognito_domain" {
  length  = 8
  special = false
  upper   = false
}

resource "aws_cognito_user_pool_domain" "main" {
  domain                = random_string.cognito_domain.result
  user_pool_id          = aws_cognito_user_pool.flip_user_pool.id
  managed_login_version = 2

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_cognito_user_pool_client" "client" {
  name         = var.flip_cognito_client
  user_pool_id = aws_cognito_user_pool.flip_user_pool.id

  # app client information
  refresh_token_validity = 5
  access_token_validity  = 60
  id_token_validity      = 60
  token_validity_units {
    refresh_token = "days"
    access_token  = "minutes"
    id_token      = "minutes"
  }
  explicit_auth_flows = [
    "ALLOW_USER_AUTH",
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_ADMIN_USER_PASSWORD_AUTH",
    "ALLOW_CUSTOM_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH"
  ]
  prevent_user_existence_errors = "ENABLED"

  # login page
  allowed_oauth_flows          = ["code", "implicit"]
  allowed_oauth_scopes         = ["email", "openid", "profile"]
  callback_urls                = ["https://localhost:443"]
  logout_urls                  = ["https://localhost:443"]
  supported_identity_providers = ["COGNITO"]

  lifecycle {
    prevent_destroy = true
  }
}

############################
# Cognito Users
############################

resource "aws_cognito_user" "admin_user" {
  user_pool_id = aws_cognito_user_pool.flip_user_pool.id
  username     = var.flip_cognito_admin_email
  attributes = {
    "email"          = var.flip_cognito_admin_email
    "email_verified" = true
  }
  password = var.ADMIN_USER_PASSWORD

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
      enabled
    ]
  }
}

resource "aws_cognito_user" "researcher_user" {
  user_pool_id = aws_cognito_user_pool.flip_user_pool.id
  username     = var.flip_cognito_researcher_email
  attributes = {
    "email"          = var.flip_cognito_researcher_email
    "email_verified" = true
  }
  password = var.ADMIN_USER_PASSWORD

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
      enabled
    ]
  }
}
