#!/bin/sh
# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generates runtime config for flip-ui. Reads env vars from the shell
# (populated by docker-compose in local dev, or by the deploy Makefile
# via .env.stag / .env.production for make deploy-ui) and writes JS to
# stdout. Consumed by public/js/window.js (local dev, via predev npm
# hook) and dist/js/window.js (deploys, via make deploy-ui).

set -eu

# Values flow into quoted JS string literals. Route them through
# JSON.stringify so a stray " or \ in a .env value can't break the
# generated file or smuggle JS. Requires `node` on PATH; both the
# dev container and `make deploy-ui` guarantee this.
json_str() {
  node -pe 'JSON.stringify(process.argv[1] || "")' -- "${1-}"
}

# Single source of truth: the canonical backend-style names used
# across the rest of the stack (.env.*, compose files, the flip-api
# container). Vite-specific duplicates used to exist but drifted out
# of sync on the deploy path and left the bundle with `userPoolId:
# undefined` at build time — now we read the canonical names directly
# and the UI picks them up at runtime via window.js.
RAW_USER_POOL_ID="${AWS_COGNITO_USER_POOL_ID:-}"
RAW_CLIENT_ID="${AWS_COGNITO_APP_CLIENT_ID:-}"

AWS_BASE_URL=$(json_str "${CENTRAL_HUB_API_URL:-http://localhost:8080/api}")
USER_POOL_ID=$(json_str "${RAW_USER_POOL_ID}")
CLIENT_ID=$(json_str "${RAW_CLIENT_ID}")
REGION=$(json_str "${AWS_REGION:-eu-west-2}")
BLACKLIST=$(json_str "${BLACKLISTED_MODEL_FILES:-}")
RELEASE=$(json_str "${RELEASE_VERSION:-}")

# MAX_REIMPORT_COUNT is emitted as a raw number, so reject non-numeric
# input rather than letting parseInt("garbage") produce NaN at runtime.
# Tolerate whitespace padding (easy .env typo); warn loudly on anything
# else so the fallback isn't silent.
MAX_REIMPORT_RAW=$(printf '%s' "${MAX_REIMPORT_COUNT:-10}" | tr -d '[:space:]')
case "$MAX_REIMPORT_RAW" in
  ''|*[!0-9]*)
    echo "generate-window-js: WARNING — MAX_REIMPORT_COUNT='${MAX_REIMPORT_COUNT-}' is not numeric; falling back to 10." >&2
    MAX_REIMPORT=10
    ;;
  *) MAX_REIMPORT="$MAX_REIMPORT_RAW" ;;
esac

if [ -z "${RAW_USER_POOL_ID}" ]; then
  echo "generate-window-js: WARNING — AWS_COGNITO_USER_POOL_ID is unset; Cognito auth will fail." >&2
fi
if [ -z "${RAW_CLIENT_ID}" ]; then
  echo "generate-window-js: WARNING — AWS_COGNITO_APP_CLIENT_ID is unset; Cognito auth will fail." >&2
fi

cat <<EOF
// Generated by flip-ui/scripts/generate-window-js.sh — do not edit by hand.
// Runtime config injected from env at dev-start (predev npm hook) or
// at deploy time (make deploy-ui). See public/js/window.js.example for shape.
window.AWS_BASE_URL            = ${AWS_BASE_URL};
window.AWS_USER_POOL_ID        = ${USER_POOL_ID};
window.AWS_CLIENT_ID           = ${CLIENT_ID};
window.AWS_REGION              = ${REGION};
window.BLACKLISTED_MODEL_FILES = ${BLACKLIST};
window.RELEASE_VERSION         = ${RELEASE};
window.MAX_REIMPORT_COUNT      = ${MAX_REIMPORT};
EOF
