#!/bin/sh
# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generates runtime config for flip-ui. Reads env vars from the shell
# (populated by docker-compose in local dev, or by the deploy Makefile
# via .env.stag / .env.production for make deploy-ui) and writes JS to
# stdout. Consumed by public/js/window.js (local dev, via predev npm
# hook) and dist/js/window.js (deploys, via make deploy-ui).

set -eu

AWS_BASE_URL="${VITE_AWS_BASE_URL:-http://localhost:8080/api}"
USER_POOL_ID="${VITE_AWS_USER_POOL_ID:-${AWS_COGNITO_USER_POOL_ID:-}}"
CLIENT_ID="${VITE_AWS_CLIENT_ID:-${AWS_COGNITO_APP_CLIENT_ID:-}}"
REGION="${VITE_AWS_REGION:-${AWS_REGION:-eu-west-2}}"
BLACKLIST="${VITE_BLACKLISTED_MODEL_FILES:-}"
RELEASE="${RELEASE_VERSION:-}"
MAX_REIMPORT="${MAX_REIMPORT_COUNT:-10}"

if [ -z "${USER_POOL_ID}" ]; then
  echo "generate-window-js: WARNING — no AWS_COGNITO_USER_POOL_ID / VITE_AWS_USER_POOL_ID set; Cognito auth will fail." >&2
fi
if [ -z "${CLIENT_ID}" ]; then
  echo "generate-window-js: WARNING — no AWS_COGNITO_APP_CLIENT_ID / VITE_AWS_CLIENT_ID set; Cognito auth will fail." >&2
fi

cat <<EOF
// Generated by flip-ui/scripts/generate-window-js.sh — do not edit by hand.
// Runtime config injected from env at dev-start (predev npm hook) or
// at deploy time (make deploy-ui). See public/js/window.js.example for shape.
window.AWS_BASE_URL            = "${AWS_BASE_URL}";
window.AWS_USER_POOL_ID        = "${USER_POOL_ID}";
window.AWS_CLIENT_ID           = "${CLIENT_ID}";
window.AWS_REGION              = "${REGION}";
window.BLACKLISTED_MODEL_FILES = "${BLACKLIST}";
window.RELEASE_VERSION         = "${RELEASE}";
window.MAX_REIMPORT_COUNT      = parseInt("${MAX_REIMPORT}", 10);
EOF
