# Copyright (c) Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# NOTE Important: any sections specified in base configs will be overridden if you specify the same sections in the
# inheriting service configs below

services:
  #################### CENTRAL HUB ####################

  flip-ui:
    image: ghcr.io/londonaicentre/flip-ui:${DOCKER_TAG}
    ports:
      - "${UI_PORT}:443"
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_LOCAL=${VITE_LOCAL}
      - VITE_AWS_BASE_URL=${VITE_AWS_BASE_URL}
      - VITE_AWS_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
      - VITE_AWS_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - VITE_AWS_REGION=${AWS_REGION}
      - VITE_BLACKLISTED_MODEL_FILES=${VITE_BLACKLISTED_MODEL_FILES}
    restart: unless-stopped
    container_name: flip-ui

  flip-api:
    image: ghcr.io/londonaicentre/flip-api:${DOCKER_TAG}
    ports:
      - "${API_PORT}:8000"
    environment:
      - ENV=production
      # - AWS_PROFILE=${AWS_PROFILE} # in production, AWS credentials are retrieved from the instance role
      - AWS_REGION=${AWS_REGION}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
      - AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_SECRET_ARN=${POSTGRES_SECRET_ARN} # in production, password is retrieved from AWS Secrets Manager
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - PRIVATE_API_KEY_HEADER=${PRIVATE_API_KEY_HEADER}
      - PRIVATE_API_KEY=${PRIVATE_API_KEY}
      - AWS_SECRET_NAME=${AWS_SECRET_NAME}
      - AWS_SES_ADMIN_EMAIL_ADDRESS=${AWS_SES_ADMIN_EMAIL_ADDRESS}
      - AWS_SES_SENDER_EMAIL_ADDRESS=${AWS_SES_SENDER_EMAIL_ADDRESS}
      - UPLOADED_MODEL_FILES_BUCKET=${UPLOADED_MODEL_FILES_BUCKET}
      - SCANNED_MODEL_FILES_BUCKET=${SCANNED_MODEL_FILES_BUCKET}
      - UPLOADED_FEDERATED_DATA_BUCKET=${UPLOADED_FEDERATED_DATA_BUCKET}
      - FL_APP_BASE_BUCKET=${FL_APP_BASE_BUCKET}
      - FL_APP_DESTINATION_BUCKET=${FL_APP_DESTINATION_BUCKET}
    restart: unless-stopped
    container_name: flip-api
