# Copyright (c) Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# NOTE Important: any sections specified in base configs will be overridden if you specify the same sections in the
# inheriting service configs below

services:
  #################### CENTRAL HUB FL ####################

  fl-api-net-1:
    container_name: flip-fl-api-net-1
    image: ${DOCKER_REGISTRY}${DOCKER_FL_API_NAME}:${DOCKER_FL_TAG}
    volumes:
      - ${FL_PROVISIONED_DIR}/net-1/certificates:/certs:ro
    environment:
      - DEBUG=${DEBUG}
      - SUPERLINK_ADDRESS=fl-server-net-1:9093
      - SUPERLINK_HEALTH_ADDRESS=fl-server-net-1:9097
      - SUPERLINK_ROOT_CERTIFICATES=/certs/ca.crt
      - SUPERNODE_HEALTH_ADDRESSES=Trust_1=trust1-fl-client-net-1-1:9098,Trust_2=trust2-fl-client-net-1-1:9098
    ports:
      - "${FL_API_PORT}:8000"
      - "5679:5679"
    depends_on:
      - fl-server-net-1
    networks:
      - default
      - shared-net-1
    restart: unless-stopped

  fl-api-net-2:
    container_name: flip-fl-api-net-2
    image: ${DOCKER_REGISTRY}${DOCKER_FL_API_NAME}:${DOCKER_FL_TAG}
    volumes:
      - ${FL_PROVISIONED_DIR}/net-2/certificates:/certs:ro
    environment:
      - DEBUG=${DEBUG}
      - SUPERLINK_ADDRESS=fl-server-net-2:9093
      - SUPERLINK_HEALTH_ADDRESS=fl-server-net-2:9097
      - SUPERLINK_ROOT_CERTIFICATES=/certs/ca.crt
      - SUPERNODE_HEALTH_ADDRESSES=Trust_1=trust1-fl-client-net-2-1:9098,Trust_2=trust2-fl-client-net-2-1:9098
    depends_on:
      - fl-server-net-2
    networks:
      - default
      - shared-net-2
    restart: unless-stopped

  fl-server-net-1:
    container_name: fl-server-net-1
    image: ${DOCKER_REGISTRY}${DOCKER_FL_SERVER_NAME}:${DOCKER_FL_TAG}
    volumes:
      # Mount the AWS credentials (needed to upload model results to S3)
      - ~/.aws/config:/root/.aws/config:ro
      - ~/.aws/sso/cache:/root/.aws/sso/cache:rw
      # Provisioned Flower secrets (only certificates are needed here)
      - ${FL_PROVISIONED_DIR}/net-1/certificates:/certs:ro
    environment:
      - NET_ID=net-1
      - LOCAL_DEV=false
      - MIN_CLIENTS=${MIN_CLIENTS}
      - IMAGES_DIR=/app/data/images
      - UPLOADED_FEDERATED_DATA_BUCKET=${UPLOADED_FEDERATED_DATA_BUCKET}
      - CENTRAL_HUB_API_URL=${CENTRAL_HUB_API_URL}
      - DATA_ACCESS_API_URL=${DATA_ACCESS_API_URL}
      - IMAGING_API_URL=${IMAGING_API_URL}
      - PRIVATE_API_KEY_HEADER=${PRIVATE_API_KEY_HEADER}
      - PRIVATE_API_KEY=${PRIVATE_API_KEY}
      - AWS_PROFILE=${AWS_PROFILE}
    command:
      - --ssl-ca-certfile
      - /certs/ca.crt
      - --ssl-certfile
      - /certs/server.pem
      - --ssl-keyfile
      - /certs/server.key
      - --enable-supernode-auth
      - --health-server-address
      - 0.0.0.0:9097
    ports:
      - 9093:9093
    networks:
      - shared-net-1
    restart: unless-stopped
    init: true

  # One-shot service to register SuperNode public keys with the SuperLink
  register-supernode-keys-net-1:
    container_name: register-supernode-keys-net-1
    # It doesn't really matter if we use FL server or FL base image here since register-supernode-keys.sh is in both
    image: ${DOCKER_REGISTRY}${DOCKER_FL_SERVER_NAME}:${DOCKER_FL_TAG}
    environment:
      - SUPERLINK_ADDRESS=fl-server-net-1:9093
    volumes:
      - ${FL_PROVISIONED_DIR}/net-1/certificates:/certs:ro
      - ${FL_PROVISIONED_DIR}/net-1/keys:/keys:ro
      - ${FL_PROVISIONED_DIR}/../register-supernode-keys.sh:/scripts/register-supernode-keys.sh:ro
    entrypoint: ["/bin/bash", "/scripts/register-supernode-keys.sh"]
    depends_on:
      - fl-server-net-1
    networks:
      - shared-net-1

  fl-server-net-2:
    container_name: fl-server-net-2
    image: ${DOCKER_REGISTRY}${DOCKER_FL_SERVER_NAME}:${DOCKER_FL_TAG}
    volumes:
      # Mount the AWS credentials (needed to upload model results to S3)
      - ~/.aws/config:/root/.aws/config:ro
      - ~/.aws/sso/cache:/root/.aws/sso/cache:rw
      # Provisioned Flower secrets (only certificates are needed here)
      - ${FL_PROVISIONED_DIR}/net-2/certificates:/certs:ro
    environment:
      - NET_ID=net-2
      - LOCAL_DEV=false
      - MIN_CLIENTS=${MIN_CLIENTS}
      - IMAGES_DIR=/app/data/images
      - UPLOADED_FEDERATED_DATA_BUCKET=${UPLOADED_FEDERATED_DATA_BUCKET}
      - CENTRAL_HUB_API_URL=${CENTRAL_HUB_API_URL}
      - DATA_ACCESS_API_URL=${DATA_ACCESS_API_URL}
      - IMAGING_API_URL=${IMAGING_API_URL}
      - PRIVATE_API_KEY_HEADER=${PRIVATE_API_KEY_HEADER}
      - PRIVATE_API_KEY=${PRIVATE_API_KEY}
      - AWS_PROFILE=${AWS_PROFILE}
    command:
      - --ssl-ca-certfile
      - /certs/ca.crt
      - --ssl-certfile
      - /certs/server.pem
      - --ssl-keyfile
      - /certs/server.key
      - --enable-supernode-auth
      - --health-server-address
      - 0.0.0.0:9097
    networks:
      - shared-net-2
    restart: unless-stopped
    init: true

  # One-shot service to register SuperNode public keys with the SuperLink
  register-supernode-keys-net-2:
    container_name: register-supernode-keys-net-2
    # It doesn't really matter if we use FL server or FL base image here since register-supernode-keys.sh is in both
    image: ${DOCKER_REGISTRY}${DOCKER_FL_SERVER_NAME}:${DOCKER_FL_TAG}
    environment:
      - SUPERLINK_ADDRESS=fl-server-net-2:9093
    volumes:
      - ${FL_PROVISIONED_DIR}/net-2/certificates:/certs:ro
      - ${FL_PROVISIONED_DIR}/net-2/keys:/keys:ro
    entrypoint: ["/bin/bash", "/scripts/register-supernode-keys.sh"]
    depends_on:
      - fl-server-net-2
    networks:
      - shared-net-2
