# Copyright (c) Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# NOTE Important: any sections specified in base configs will be overridden if you specify the same sections in the
# inheriting service configs below

services:

  fl-client-net-1:
    image: ${DOCKER_REGISTRY}${DOCKER_FL_CLIENT_NAME}:${DOCKER_FL_TAG}
    volumes:
      # Mount the base images download directory to share images downloaded from XNAT with FL clients
      - ${BASE_IMAGES_DOWNLOAD_DIR}:/app/data/images
      # Provisioned Flower secrets (certificates, keys)
      - ${FL_PROVISIONED_DIR}/net-1/certificates:/certs:ro
      - ${FL_PROVISIONED_DIR}/net-1/keys:/keys:ro
    environment:
      - NET_ID=net-1
      - SUPERNODE_NAME=Trust_${TRUST_NUMBER}
      - NUM_AVAILABLE_GPUS=${NUM_AVAILABLE_GPUS}
      - MEMORY_PER_GPU_IN_GIB=${MEMORY_PER_GPU_IN_GIB}
      - LOCAL_DEV=false
      - MIN_CLIENTS=${MIN_CLIENTS}
      - IMAGES_DIR=/app/data/images
      - UPLOADED_FEDERATED_DATA_BUCKET=${UPLOADED_FEDERATED_DATA_BUCKET}
      - CENTRAL_HUB_API_URL=${CENTRAL_HUB_API_URL}
      - DATA_ACCESS_API_URL=${DATA_ACCESS_API_URL}
      - IMAGING_API_URL=${IMAGING_API_URL}
      - PRIVATE_API_KEY_HEADER=${PRIVATE_API_KEY_HEADER}
      - PRIVATE_API_KEY=${PRIVATE_API_KEY}
    command:
      - --root-certificates
      - /certs/ca.crt
      - --superlink
      - fl-server-net-1:9092
      - --auth-supernode-private-key
      - /keys/supernode_credentials_${TRUST_NUMBER}
      - --clientappio-api-address
      - ${SUPERNODE_1_CLIENTAPPIO_API_ADDRESS:-127.0.0.1:9094}
      - --health-server-address
      - ${SUPERNODE_1_HEALTH_SERVER_BIND_ADDRESS:-0.0.0.0:9098}
    networks:
      - default
      - deploy_shared-net-1
    shm_size: '32gb'
    gpus: all

  fl-client-net-2:
    image: ${DOCKER_REGISTRY}${DOCKER_FL_CLIENT_NAME}:${DOCKER_FL_TAG}
    volumes:
      # Mount the base images download directory to share images downloaded from XNAT with FL clients
      - ${BASE_IMAGES_DOWNLOAD_DIR}:/app/data/images
      # Provisioned Flower secrets (certificates, keys)
      - ${FL_PROVISIONED_DIR}/net-2/certificates:/certs:ro
      - ${FL_PROVISIONED_DIR}/net-2/keys:/keys:ro
    environment:
      - NET_ID=net-2
      - SUPERNODE_NAME=Trust_${TRUST_NUMBER}
      - NUM_AVAILABLE_GPUS=${NUM_AVAILABLE_GPUS}
      - MEMORY_PER_GPU_IN_GIB=${MEMORY_PER_GPU_IN_GIB}
      - LOCAL_DEV=false
      - MIN_CLIENTS=${MIN_CLIENTS}
      - IMAGES_DIR=/app/data/images
      - UPLOADED_FEDERATED_DATA_BUCKET=${UPLOADED_FEDERATED_DATA_BUCKET}
      - CENTRAL_HUB_API_URL=${CENTRAL_HUB_API_URL}
      - DATA_ACCESS_API_URL=${DATA_ACCESS_API_URL}
      - IMAGING_API_URL=${IMAGING_API_URL}
      - PRIVATE_API_KEY_HEADER=${PRIVATE_API_KEY_HEADER}
      - PRIVATE_API_KEY=${PRIVATE_API_KEY}
    command:
      - --root-certificates
      - /certs/ca.crt
      - --superlink
      - fl-server-net-2:9092
      - --auth-supernode-private-key
      - /keys/supernode_credentials_${TRUST_NUMBER}
      - --clientappio-api-address
      - ${SUPERNODE_2_CLIENTAPPIO_API_ADDRESS:-127.0.0.1:9095}
      - --health-server-address
      - ${SUPERNODE_2_HEALTH_SERVER_BIND_ADDRESS:-0.0.0.0:9098}
    networks:
      - default
      - deploy_shared-net-2
    shm_size: '32gb'
    gpus: all
