# Copyright (c) Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  trust-api:
    environment:
      - DEBUG=${DEBUG}
    ports:
      - "${TRUST_DEBUG_PORT}:${TRUST_DEBUG_PORT}"

  imaging-api:
    environment:
      - DEBUG=${DEBUG}
    ports:
      - "${IMAGING_DEBUG_PORT}:${IMAGING_DEBUG_PORT}"
  data-access-api:
    environment:
      - DEBUG=${DEBUG}
    ports:
      - "${DATA_ACCESS_DEBUG_PORT}:${DATA_ACCESS_DEBUG_PORT}"
