# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FLIP Cognito user pool + client + domain + seed users.
#
# The resource addresses here are load-bearing for the prod stack because
# the production state predates this module. When introducing the module
# to an already-deployed environment, move each resource in state first:
#
#   terraform state mv aws_cognito_user_pool.flip_user_pool \
#       module.cognito.aws_cognito_user_pool.flip_user_pool
#   terraform state mv random_string.cognito_domain \
#       module.cognito.random_string.cognito_domain
#   terraform state mv aws_cognito_user_pool_domain.main \
#       module.cognito.aws_cognito_user_pool_domain.main
#   terraform state mv aws_cognito_user_pool_client.client \
#       module.cognito.aws_cognito_user_pool_client.client
#   terraform state mv aws_cognito_user.admin_user \
#       module.cognito.aws_cognito_user.admin_user
#   terraform state mv aws_cognito_user.researcher_user \
#       module.cognito.aws_cognito_user.researcher_user
#
# Otherwise terraform tries to destroy + recreate the pool, which the
# prevent_destroy lifecycle block will (correctly) refuse.

resource "aws_cognito_user_pool" "flip_user_pool" {
  name                     = var.user_pool_name
  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]
  schema {
    name                = "email"
    attribute_data_type = "String"
    mutable             = false
    required            = true
  }

  # Cognito email templates for admin-created users and password reset flows.
  # Templates live at the caller's path (typically templates/cognito/) so the
  # Python testing script in deploy/providers/AWS/test_email_templates.py can
  # load the same files without chasing them into every module that needs them.
  # See: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/userguide/user-pool-email.html
  # Color scheme matches flip-ui: https://github.com/londonaicentre/FLIP/blob/develop/flip-ui/tailwind.config.js
  # Primary: #61366e (purple), Secondary: #9452A8 (lighter purple), Accent: #301A37 (dark purple)
  admin_create_user_config {
    invite_message_template {
      # {username} placeholder: Cognito username for the invited user
      # {####} placeholder: 6-character temporary password generated by Cognito
      email_subject = "Welcome to FLIP – Federated Learning and Interoperability Platform"
      # {flip_alb_subdomain} is not a native Cognito placeholder — substitute it with the sign-in hostname at plan time.
      email_message = replace(file("${var.templates_dir}/invite.html"), "{flip_alb_subdomain}", var.sign_in_hostname)
      # SMS fallback message for users without email or additional verification
      sms_message = "You've been invited to FLIP. Username: {username}, Temporary password: {####}. Sign in at https://${var.sign_in_hostname}"
    }
  }

  verification_message_template {
    default_email_option = "CONFIRM_WITH_CODE"
    email_subject        = "Password Reset Request – FLIP"
    email_message        = file("${var.templates_dir}/password_reset_code.html")
    sms_message          = "Your FLIP password reset code is: {####}. Valid for 24 hours."

    email_subject_by_link = "Password Reset – FLIP"
    email_message_by_link = file("${var.templates_dir}/password_reset_link.html")
  }

  # MFA is enforced at the application layer, not at the pool. The pool
  # is OPTIONAL because Cognito has no admin API to delete a user's
  # verified TOTP secret — with the pool set to ON, an admin reset
  # (AdminSetUserMFAPreference Enabled=False) leaves the old secret
  # registered and Cognito keeps challenging SOFTWARE_TOKEN_MFA on the
  # next sign-in, so the user is asked for a code they no longer have.
  # With OPTIONAL, disabling the preference actually takes effect:
  # Cognito signs the user in without a challenge, and the app layer
  # (flip-api verify_token + flip-ui router guard) catches any user
  # whose UserMFASettingList lacks SOFTWARE_TOKEN_MFA and funnels them
  # through the post-auth enrolment page. First-time users follow the
  # same path — they sign in, mfaEnabled=false, and are routed to
  # mfa-setup before any protected route lets them through.
  # SMS MFA is intentionally disabled (no SNS dependency, no SIM-swap risk).
  mfa_configuration = "OPTIONAL"

  software_token_mfa_configuration {
    enabled = true
  }

  deletion_protection = "ACTIVE"
  lifecycle {
    prevent_destroy = true
    # Cognito's UpdateUserPool API refuses to accept a schema payload on
    # any update, even one that matches the existing schema byte-for-byte
    # ("cannot modify or remove schema items"). Schemas are immutable
    # after pool creation, so ignore them here — the block above is only
    # used when the pool is created from scratch.
    ignore_changes = [schema]
  }
}

resource "random_string" "cognito_domain" {
  length  = 8
  special = false
  upper   = false

  # `terraform import` on random_string cannot accept generator-config
  # arguments; the imported state defaults to special=true/upper=true even
  # when the module says otherwise, which would force a replacement of the
  # (prevent_destroy-protected) hosted-UI domain. Once the resource is in
  # state, only the resulting `result` string matters — ignore config
  # drift so imports settle cleanly.
  lifecycle {
    ignore_changes = [length, special, upper, numeric, min_special, min_numeric, min_upper, min_lower, override_special]
  }
}

resource "aws_cognito_user_pool_domain" "main" {
  domain                = random_string.cognito_domain.result
  user_pool_id          = aws_cognito_user_pool.flip_user_pool.id
  managed_login_version = 2

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_cognito_user_pool_client" "client" {
  name         = var.client_name
  user_pool_id = aws_cognito_user_pool.flip_user_pool.id

  refresh_token_validity = 5
  access_token_validity  = 60
  id_token_validity      = 60
  token_validity_units {
    refresh_token = "days"
    access_token  = "minutes"
    id_token      = "minutes"
  }
  explicit_auth_flows = [
    "ALLOW_USER_AUTH",
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_ADMIN_USER_PASSWORD_AUTH",
    "ALLOW_CUSTOM_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH"
  ]
  prevent_user_existence_errors = "ENABLED"

  allowed_oauth_flows          = ["code", "implicit"]
  allowed_oauth_scopes         = ["email", "openid", "profile"]
  callback_urls                = var.callback_urls
  logout_urls                  = var.logout_urls
  supported_identity_providers = ["COGNITO"]

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_cognito_user" "admin_user" {
  user_pool_id = aws_cognito_user_pool.flip_user_pool.id
  username     = var.admin_email
  attributes = {
    "email"          = var.admin_email
    "email_verified" = true
  }
  password = var.seed_user_password

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
      enabled
    ]
  }
}

resource "aws_cognito_user" "researcher_user" {
  # Some environments (e.g. dev) may not want a second seed user.
  count = var.researcher_email == "" ? 0 : 1

  user_pool_id = aws_cognito_user_pool.flip_user_pool.id
  username     = var.researcher_email
  attributes = {
    "email"          = var.researcher_email
    "email_verified" = true
  }
  password = var.seed_user_password

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
      enabled
    ]
  }
}
