# Portions derived from the XNAT docker-compose project
# Copyright (c) 2020, Washington University School of Medicine
# Licensed under the BSD 2-Clause License.
# SPDX-License-Identifier: BSD-2-Clause
#
# Modifications Copyright (c) 2026,
# Guy's and St Thomas' NHS Foundation Trust & King's College London

# version: '3.7'
services:
  xnat-web:
    image: ${DOCKER_REGISTRY}xnat-web:${DOCKER_TAG}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    ports:
      - ${XNAT_PORT}:8080
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME} -XX:+UseG1GC -Djava.awt.headless=true -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=6 -XX:+UseStringDeduplication
      - XNAT_HOME=${XNAT_HOME}
      - XNAT_ADMIN_USER=${XNAT_ADMIN_USER}
      - XNAT_ADMIN_INITIAL_PASSWORD=${XNAT_ADMIN_INITIAL_PASSWORD}
      - XNAT_ADMIN_PASSWORD=${XNAT_ADMIN_PASSWORD}
      - XNAT_SERVICE_USER=${XNAT_SERVICE_USER}
      - XNAT_SERVICE_PASSWORD=${XNAT_SERVICE_PASSWORD}
      - XNAT_PORT=${XNAT_PORT}
      - PACS_DICOM_PORT=${PACS_DICOM_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db

  xnat-db:
    image: ${DOCKER_REGISTRY}xnat-db:${DOCKER_TAG}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      #
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${XNAT_DATASOURCE_ADMIN_PASSWORD}
      - POSTGRES_DB=${XNAT_DATASOURCE_NAME}
      # variables for the sql script
      - XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}

  xnat-nginx:
    image: ${DOCKER_REGISTRY}xnat-nginx:${DOCKER_TAG}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    # ports:
    #   - "80:80"
    depends_on:
      - xnat-web

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    external: true
