# Copyright (c) Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: FLIP UI CI

on:
  push:
    branches: [main, develop]
    paths:
      - "flip-ui/**"
      - ".github/workflows/test_flip_ui.yml"
  pull_request:
    branches: [main, develop]

jobs:
  flip-ui:
    runs-on: ubuntu-latest
    environment: flip
    defaults:
      run:
        working-directory: ./flip-ui

    env:
      VITE_LOCAL: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4 #
        with:
          node-version: "22" # Specify the Node.js version you need
      - name: Install dependencies
        run: npm install

      - name: Run tests with npm
        run: npm run test:unit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: flip-ui/coverage/cobertura-coverage.xml
          flags: flip-ui
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
